"""Regression guard for bmad-loop#64: the bmad-loop-setup cleanup scripts must
never delete live, manifest-tracked BMAD config/state.

On a BMAD v6 install ``_bmad/core/``, ``_bmad/<module>/`` and ``_bmad/_config/``
hold live config + installer manifests (no staged ``SKILL.md``). The setup scripts
used to hardcode ``core`` and ``--also-remove _config`` into their delete lists,
destroying that shared state. These tests run the real scripts as the SKILL.md
documents and assert only genuine redundant skill-payload dirs are ever removed.

Root cause is shared with upstream ``bmad-code-org/bmad-builder#96``.
"""

from __future__ import annotations

import csv
import importlib.util
import json
import os
import stat
import subprocess
import sys
import tomllib
from pathlib import Path

import pytest
import yaml

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "src" / "bmad_loop" / "data" / "skills" / "bmad-loop-setup" / "scripts"
ASSETS = REPO / "src" / "bmad_loop" / "data" / "skills" / "bmad-loop-setup" / "assets"


def _run(script: str, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPTS / script), *args],
        capture_output=True,
        text=True,
    )


def _run_json(script: str, *args: str) -> dict:
    proc = _run(script, *args)
    assert (
        proc.returncode == 0
    ), f"{script} exit {proc.returncode}\nOUT:{proc.stdout}\nERR:{proc.stderr}"
    return json.loads(proc.stdout)


def _v6_bmad(tmp_path: Path) -> Path:
    """A realistic BMAD v6 `_bmad/` tree: live config + manifest, no staged skills."""
    bmad = tmp_path / "_bmad"
    (bmad / "core").mkdir(parents=True)
    (bmad / "core" / "config.yaml").write_text("user_name: BMad\noutput_folder: out\n")
    (bmad / "core" / "module-help.csv").write_text("module,skill\ncore,x\n")
    (bmad / "bmm").mkdir()
    (bmad / "bmm" / "config.yaml").write_text("dev_story_location: docs\n")
    (bmad / "bmad-loop").mkdir()
    (bmad / "bmad-loop" / "config.yaml").write_text("cadence: fast\n")
    cfg = bmad / "_config"
    cfg.mkdir()
    (cfg / "manifest.yaml").write_text("installation:\n  version: 6.10.0\n")
    (cfg / "files-manifest.csv").write_text("path,hash\n_bmad/core/config.yaml,abc\n")
    (cfg / "bmad-help.csv").write_text("module,skill\ncore,x\n")
    return bmad


# A human-authored custom layer: comments, blank lines, an unrelated table.
# BMAD documents _bmad/custom/config.toml as the layer the installer never touches,
# so merge-config must edit it surgically and leave everything else byte-identical.
_CUSTOM_TOML = """\
# Custom overrides — the BMAD installer never touches this file.
# Values here win over the generated layers.

[modules.my-thing]
# hand-written note about my-thing
enabled = true
"""

# The assembled catalog `/bmad-help` reads: the installer's concatenation of every
# per-module `_bmad/<module>/module-help.csv`, with the real v6.10 column names.
_ASSEMBLED_CATALOG = """\
module,skill,display-name,menu-code,description,action,args,phase,preceded-by,followed-by,required,output-location,outputs
BMad Method,bmad-brainstorming,Brainstorm Project,BP,Expert guided facilitation.,,,1-analysis,,,false,planning_artifacts,brainstorming session
BMad Method,bmad-create-prd,Create PRD,PRD,Product requirements document.,,,2-plan,,,false,planning_artifacts,PRD
Core,bmad-help,BMad Help,H,Analyze state and recommend the next skill.,,,anytime,,,false,,recommendation
"""


def _v610_bmad(tmp_path: Path) -> Path:
    """A BMAD v6.10 `_bmad/` tree: consolidated TOML config + a custom layer.

    Same live per-module YAML as `_v6_bmad` (v6.10 still ships those and the
    manifest still tracks them) plus the four TOML layers the v6.10 resolver
    actually reads. The presence of `config.toml` is what selects the layout.
    `_config/bmad-help.csv` is the assembled help catalog, the only one
    `/bmad-help` reads.
    """
    bmad = _v6_bmad(tmp_path)
    (bmad / "_config" / "bmad-help.csv").write_text(_ASSEMBLED_CATALOG)
    (bmad / "config.toml").write_text(
        "# Generated by the BMAD installer.\n"
        "[core]\n"
        'user_name = "BMad"\n'
        'output_folder = "out"\n'
        "\n"
        "[modules.bmm]\n"
        'name = "BMad Method"\n'
        'version = "6.10.0"\n'
    )
    (bmad / "config.user.toml").write_text('[core]\nuser_name = "BMad"\n')
    (bmad / "custom").mkdir()
    (bmad / "custom" / "config.toml").write_text(_CUSTOM_TOML)
    return bmad


def _answers(tmp_path: Path, payload: dict) -> Path:
    path = tmp_path / "answers.json"
    path.write_text(json.dumps(payload))
    return path


def _merge_config(bmad: Path, answers: Path, module_yaml: Path | None = None, *extra: str) -> dict:
    return _run_json(
        "merge-config.py",
        "--bmad-dir",
        str(bmad),
        "--module-yaml",
        str(module_yaml or ASSETS / "module.yaml"),
        "--answers",
        str(answers),
        *extra,
    )


def _merge_help(bmad: Path, *extra: str) -> dict:
    return _run_json(
        "merge-help-csv.py",
        "--bmad-dir",
        str(bmad),
        "--source",
        str(ASSETS / "module-help.csv"),
        *extra,
    )


def _load_script(name: str):
    """Import a hyphen-named setup script as a module, for unit-level assertions.

    The scripts ship standalone into user projects, so they are not importable as
    package modules; almost every test drives them as subprocesses instead. This is
    for the few assertions that need a single function in isolation.
    """
    spec = importlib.util.spec_from_file_location(name.replace("-", "_")[:-3], SCRIPTS / name)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _csv_rows(path: Path) -> tuple[list[str], list[list[str]]]:
    """Read a CSV as (header, data_rows)."""
    rows = list(csv.reader(path.read_text(encoding="utf-8").splitlines()))
    return rows[0], rows[1:]


def _skills_dir(tmp_path: Path, *installed: str) -> Path:
    skills = tmp_path / ".claude" / "skills"
    skills.mkdir(parents=True)
    for name in installed:
        d = skills / name
        d.mkdir()
        (d / "SKILL.md").write_text(f"# {name}\n")
    return skills


# ---------------------------------------------------------------- cleanup-legacy


def test_cleanup_preserves_core_and_config_on_v6(tmp_path):
    """The documented invocation must be a no-op on a v6 install."""
    bmad = _v6_bmad(tmp_path)
    skills = _skills_dir(tmp_path)  # nothing installed — bmad-loop dir is config-bearing

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "bmad-loop",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == []
    assert (bmad / "bmad-loop" / "config.yaml").exists()
    assert (bmad / "core" / "config.yaml").exists()
    assert (bmad / "_config" / "manifest.yaml").exists()
    protected = {p["dir"] for p in result["directories_protected"]}
    assert "bmad-loop" in protected


def test_cleanup_refuses_explicit_core_and_config(tmp_path):
    """Even an explicit --module-code core / --also-remove _config must not delete them."""
    bmad = _v6_bmad(tmp_path)
    skills = _skills_dir(tmp_path)

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "core",
        "--also-remove",
        "_config",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == []
    assert (bmad / "core" / "config.yaml").exists()
    assert (bmad / "_config" / "manifest.yaml").exists()
    assert (bmad / "_config" / "files-manifest.csv").exists()


def test_cleanup_removes_genuine_redundant_payload(tmp_path):
    """A dir with an installed SKILL.md payload and no config IS cleaned."""
    bmad = _v6_bmad(tmp_path)
    payload = bmad / "legacy-mod"
    payload.mkdir()
    (payload / "SKILL.md").write_text("# legacy-mod\n")  # skill name == 'legacy-mod'
    skills = _skills_dir(tmp_path, "legacy-mod")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy-mod",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == ["legacy-mod"]
    assert not payload.exists()
    # protecting v6 state is unaffected
    assert (bmad / "core" / "config.yaml").exists()


def test_cleanup_errors_when_payload_skill_not_installed(tmp_path):
    """A payload dir whose skill is missing from skills-dir is an error, not a delete."""
    bmad = _v6_bmad(tmp_path)
    payload = bmad / "legacy-mod"
    payload.mkdir()
    (payload / "SKILL.md").write_text("# legacy-mod\n")
    skills = _skills_dir(tmp_path)  # legacy-mod NOT installed

    proc = _run(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy-mod",
        "--skills-dir",
        str(skills),
    )
    assert proc.returncode == 1
    assert payload.exists()
    err = json.loads(proc.stdout)
    assert err["status"] == "error"
    assert "legacy-mod" in err["missing_skills"]


def test_cleanup_reports_removable_dir_absent_at_removal_time(tmp_path):
    """A removable dir gone by removal time must surface in directories_not_found.

    Regression for bmad-loop#73 review: cleanup_directories()'s not_found used to be
    discarded, so such a dir silently vanished from every JSON list. Exercised
    deterministically via a nested --also-remove target whose parent is removed first.
    """
    bmad = _v6_bmad(tmp_path)
    # 'legacy/' has no SKILL.md of its own; its only payload is 'legacy/child'.
    (bmad / "legacy" / "child").mkdir(parents=True)
    (bmad / "legacy" / "child" / "SKILL.md").write_text("# child\n")
    skills = _skills_dir(tmp_path, "child")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy",
        "--also-remove",
        "legacy/child",  # removed together with its parent 'legacy' earlier in the run
        "--skills-dir",
        str(skills),
    )

    # Parent is removed; the nested child is already gone by its turn but must still
    # be reported rather than silently dropped from all output lists.
    assert result["directories_removed"] == ["legacy"]
    assert "legacy/child" in result["directories_not_found"]
    assert not (bmad / "legacy").exists()


def test_cleanup_protects_core_by_name_even_as_pure_payload(tmp_path):
    """core/ is never removed — even holding only a SKILL.md payload and no config.

    Regression for bmad-loop#73 review: the docstring promised 'core' is never
    removed, but only _config was protected by name; a marker-less core payload
    slipped through the config-bearing check.
    """
    bmad = tmp_path / "_bmad"
    core = bmad / "core"
    core.mkdir(parents=True)
    (core / "SKILL.md").write_text("# core\n")  # no config markers at all
    skills = _skills_dir(tmp_path, "core")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "core",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == []
    assert (core / "SKILL.md").exists()
    protected = {p["dir"] for p in result["directories_protected"]}
    assert "core" in protected


def test_cleanup_protects_dir_with_nested_live_config(tmp_path):
    """A config marker nested below the top level still protects the whole dir.

    Regression for bmad-loop#73 review: is_config_bearing() only looked at the
    candidate's top level while skill discovery was recursive, so a dir with a
    SKILL.md and deeper live config was misclassified as a removable payload.
    """
    bmad = _v6_bmad(tmp_path)
    legacy = bmad / "legacy-mod"
    (legacy / "sub").mkdir(parents=True)
    (legacy / "SKILL.md").write_text("# legacy-mod\n")
    (legacy / "sub" / "config.yaml").write_text("live: true\n")  # nested live state
    skills = _skills_dir(tmp_path, "legacy-mod")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy-mod",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == []
    assert (legacy / "sub" / "config.yaml").exists()
    protected = {p["dir"] for p in result["directories_protected"]}
    assert "legacy-mod" in protected


def test_cleanup_removes_payload_whose_skill_ships_marker_named_assets(tmp_path):
    """Marker-named files inside a SKILL.md-bearing subtree are payload, not live state.

    Staged skill payloads legitimately ship files like assets/module-help.csv
    (bmad-loop-setup itself does); the recursive config scan must not
    false-protect such a dir or the documented bauto rename-cleanup would no-op.
    """
    bmad = _v6_bmad(tmp_path)
    legacy = bmad / "legacy-mod"
    foo = legacy / "skills" / "foo"
    (foo / "assets").mkdir(parents=True)
    (foo / "SKILL.md").write_text("# foo\n")
    (foo / "assets" / "module-help.csv").write_text("module,skill\nfoo,x\n")
    skills = _skills_dir(tmp_path, "foo")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy-mod",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == ["legacy-mod"]
    assert not legacy.exists()
    # live v6 state is untouched
    assert (bmad / "core" / "config.yaml").exists()


# ---------------------------------------------------------------- merge-config


def test_merge_config_preserves_legacy_configs(tmp_path):
    bmad = _v6_bmad(tmp_path)
    answers = tmp_path / "answers.json"
    answers.write_text("{}")

    result = _run_json(
        "merge-config.py",
        "--bmad-dir",
        str(bmad),
        "--config-path",
        str(bmad / "config.yaml"),
        "--user-config-path",
        str(bmad / "config.user.yaml"),
        "--module-yaml",
        str(ASSETS / "module.yaml"),
        "--answers",
        str(answers),
        "--legacy-dir",
        str(bmad),
    )

    assert result["legacy_configs_deleted"] == []
    # live per-module + core config survive
    assert (bmad / "core" / "config.yaml").exists()
    assert (bmad / "bmad-loop" / "config.yaml").exists()
    # and the consolidated config was still written
    assert (bmad / "config.yaml").exists()


# --------------------------------------------------- merge-config (toml layout)
#
# bmad-loop#258: BMAD v6.10 consolidated onto TOML and its resolver reads only
# config.toml / config.user.toml / custom/config.toml / custom/config.user.toml.
# Registration must land in custom/config.toml — and nowhere else.


def test_merge_config_toml_layout_writes_custom_table(tmp_path):
    """The module table lands in custom/config.toml and BMAD's own reader accepts it."""
    bmad = _v610_bmad(tmp_path)

    result = _merge_config(bmad, _answers(tmp_path, {}))

    assert result["status"] == "success"
    assert result["layout"] == "toml"
    assert result["table_replaced"] is False
    assert result["toml_validated"] is True
    custom = bmad / "custom" / "config.toml"
    assert Path(result["config_path"]) == custom.resolve()
    assert set(result["module_keys"]) == {"name", "description", "version", "default_selected"}

    text = custom.read_text()
    assert "[modules.bmad-loop]" in text
    assert 'name = "BMAD Loop Skills"' in text
    assert 'version = "0.9.0"' in text
    assert "default_selected = false" in text

    table = tomllib.loads(text)["modules"]["bmad-loop"]
    assert table["name"] == "BMAD Loop Skills"
    assert table["version"] == "0.9.0"
    assert table["default_selected"] is False
    assert table["description"].startswith("Automation-mode skills")


def test_merge_config_toml_layout_preserves_custom_comments(tmp_path):
    """Every pre-existing comment and unrelated table survives verbatim.

    custom/config.toml is human-authored; the edit is surgical, never a
    parse-and-re-emit. Covers both an append (no table yet) and a replace with a
    following commented table — whose preamble belongs to *it*, not to our span.
    """
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    answers = _answers(tmp_path, {})

    _merge_config(bmad, answers)

    after_append = custom.read_text()
    assert after_append.startswith(_CUSTOM_TOML)
    for line in _CUSTOM_TOML.splitlines():
        assert line in after_append.splitlines()

    # Now our table has a hand-written neighbour *below* it.
    trailing = "\n# notes that belong to the next table\n[tool.something]\nx = 1\n"
    custom.write_text(after_append + trailing)

    result = _merge_config(bmad, answers)

    final = custom.read_text()
    assert result["table_replaced"] is True
    assert final.count("[modules.bmad-loop]") == 1
    assert final.startswith(_CUSTOM_TOML)
    assert final.endswith(trailing)
    assert "# notes that belong to the next table" in final
    assert tomllib.loads(final)["tool"]["something"]["x"] == 1


def test_merge_config_toml_layout_writes_no_yaml(tmp_path):
    """No config.yaml / config.user.yaml is created, and the installer layer is untouched."""
    bmad = _v610_bmad(tmp_path)
    installer_toml = (bmad / "config.toml").read_text()

    result = _merge_config(bmad, _answers(tmp_path, {}))

    assert not (bmad / "config.yaml").exists()
    assert not (bmad / "config.user.yaml").exists()
    assert result["user_config_path"] is None
    assert result["user_keys"] == []
    # installer-owned layers are read-only to us
    assert (bmad / "config.toml").read_text() == installer_toml
    assert (bmad / "config.user.toml").read_text() == '[core]\nuser_name = "BMad"\n'


def test_merge_config_toml_layout_never_writes_core_values(tmp_path):
    """Core answers leave no trace: the custom layer wins over the installer layer.

    Pinning user_name / output_folder here would override every future installer
    answer, so on the TOML layout core config stays installer-owned.
    """
    bmad = _v610_bmad(tmp_path)
    answers = _answers(
        tmp_path,
        {
            "core": {
                "user_name": "Zaphod",
                "output_folder": "docs/generated",
                "communication_language": "Betelgeusian",
            }
        },
    )

    result = _merge_config(bmad, answers)

    text = (bmad / "custom" / "config.toml").read_text()
    for leaked in ("Zaphod", "user_name", "output_folder", "Betelgeusian"):
        assert leaked not in text
    assert result["core_updated"] is False
    assert result["user_keys"] == []
    assert not (bmad / "config.user.yaml").exists()


def test_merge_config_toml_upsert_is_idempotent(tmp_path):
    """Two runs leave exactly one table; a version bump replaces, never duplicates."""
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    answers = _answers(tmp_path, {})

    first = _merge_config(bmad, answers)
    second = _merge_config(bmad, answers)

    assert first["table_replaced"] is False
    assert second["table_replaced"] is True
    assert custom.read_text().count("[modules.bmad-loop]") == 1

    bumped = tmp_path / "module.yaml"
    bumped.write_text(
        (ASSETS / "module.yaml")
        .read_text()
        .replace("module_version: 0.9.0", "module_version: 1.2.3")
    )
    third = _merge_config(bmad, answers, bumped)

    text = custom.read_text()
    assert third["table_replaced"] is True
    assert text.count("[modules.bmad-loop]") == 1
    assert 'version = "1.2.3"' in text
    assert '"0.9.0"' not in text
    assert tomllib.loads(text)["modules"]["bmad-loop"]["version"] == "1.2.3"


def test_merge_config_toml_reports_orphans_without_deleting(tmp_path):
    """Inert pre-6.10 leftovers are reported, never removed (bmad-loop#64)."""
    bmad = _v610_bmad(tmp_path)
    (bmad / "config.yaml").write_text("bmad-loop:\n  name: BMAD Loop Skills\n")
    (bmad / "module-help.csv").write_text("module,skill\nBMAD Automator Skills,bauto-sweep\n")
    # a malformed leftover must be reported, not raised on
    (bmad / "config.user.yaml").write_text("this: [is: not: valid\n")

    result = _merge_config(bmad, _answers(tmp_path, {}), None, "--legacy-dir", str(bmad))

    orphans = {Path(o["path"]).name: o["has_module_entries"] for o in result["orphans_detected"]}
    assert orphans == {
        "config.yaml": True,
        "config.user.yaml": False,
        "module-help.csv": True,
    }
    assert result["legacy_configs_deleted"] == []
    # every reported orphan survives, byte for byte
    assert (bmad / "config.yaml").read_text() == "bmad-loop:\n  name: BMAD Loop Skills\n"
    assert (bmad / "config.user.yaml").exists()
    assert (bmad / "module-help.csv").exists()
    # ...as does the live per-module config --legacy-dir reads
    assert (bmad / "core" / "config.yaml").exists()
    assert (bmad / "bmad-loop" / "config.yaml").exists()


def test_merge_config_yaml_layout_unchanged(tmp_path):
    """No config.toml ⇒ today's legacy behavior, tagged layout == "yaml"."""
    bmad = _v6_bmad(tmp_path)
    assert not (bmad / "config.toml").exists()

    result = _merge_config(
        bmad,
        _answers(tmp_path, {"core": {"user_name": "BMad"}}),
        None,
        "--config-path",
        str(bmad / "config.yaml"),
        "--user-config-path",
        str(bmad / "config.user.yaml"),
        "--legacy-dir",
        str(bmad),
    )

    assert result["layout"] == "yaml"
    assert result["orphans_detected"] == []
    assert result["legacy_configs_deleted"] == []
    assert result["module_code"] == "bmad-loop"
    assert result["core_updated"] is True
    assert result["user_keys"] == ["user_name"]
    assert (bmad / "config.yaml").exists()
    assert (bmad / "config.user.yaml").exists()
    assert not (bmad / "custom").exists()

    config = yaml.safe_load((bmad / "config.yaml").read_text())
    assert config["bmad-loop"]["name"] == "BMAD Loop Skills"


def test_merge_config_yaml_layout_requires_legacy_paths(tmp_path):
    """The legacy branch fails loudly when its layout-specific paths are missing."""
    bmad = _v6_bmad(tmp_path)

    proc = _run(
        "merge-config.py",
        "--bmad-dir",
        str(bmad),
        "--module-yaml",
        str(ASSETS / "module.yaml"),
        "--answers",
        str(_answers(tmp_path, {})),
    )

    assert proc.returncode == 1
    error = json.loads(proc.stderr)
    assert error["status"] == "error"
    assert "--config-path" in error["error"]
    assert not (bmad / "config.yaml").exists()


# ---------------------------------------------------------------- merge-help-csv


def test_merge_help_csv_preserves_legacy_csvs(tmp_path):
    bmad = _v6_bmad(tmp_path)

    result = _run_json(
        "merge-help-csv.py",
        "--bmad-dir",
        str(bmad),
        "--target",
        str(bmad / "module-help.csv"),
        "--source",
        str(ASSETS / "module-help.csv"),
        "--legacy-dir",
        str(bmad),
        "--module-code",
        "bmad-loop",
    )

    assert result["legacy_csvs_deleted"] == []
    assert (bmad / "core" / "module-help.csv").exists()
    assert (bmad / "module-help.csv").exists()


# ------------------------------------------------- merge-help-csv (toml layout)
#
# bmad-loop#258: `/bmad-help` reads only `_bmad/_config/bmad-help.csv`, the
# assembled concat of the per-module `_bmad/<module>/module-help.csv` files. The
# root `_bmad/module-help.csv` this script used to write is manifest-untracked and
# read by nothing, so on v6.10 the rows must land in both installer-shaped files.


def test_merge_help_toml_writes_per_module_csv(tmp_path):
    """Our rows land in `_bmad/<module-code>/module-help.csv` with the source header."""
    bmad = _v610_bmad(tmp_path)

    result = _merge_help(bmad, "--module-code", "bmad-loop")

    assert result["status"] == "success"
    assert result["layout"] == "toml"
    per_module = bmad / "bmad-loop" / "module-help.csv"
    assert Path(result["module_help_path"]) == per_module.resolve()

    source_header, source_rows = _csv_rows(ASSETS / "module-help.csv")
    header, rows = _csv_rows(per_module)
    assert header == source_header
    assert rows == source_rows  # wholly ours, so a full overwrite
    assert {row[0] for row in rows} == {"BMAD Loop Skills"}
    # the real column names, not the stale after/before the HEADER constant carried
    assert "preceded-by" in header and "followed-by" in header
    assert "after" not in header and "before" not in header


def test_merge_help_toml_merges_assembled_catalog(tmp_path):
    """The catalog gains our rows and keeps every other module's, header included."""
    bmad = _v610_bmad(tmp_path)
    catalog = bmad / "_config" / "bmad-help.csv"
    before_header, before_rows = _csv_rows(catalog)

    result = _merge_help(bmad, "--module-code", "bmad-loop")

    assert Path(result["catalog_path"]) == catalog.resolve()
    assert result["catalog_existed"] is True
    assert result["module_codes"] == ["BMAD Loop Skills"]
    assert result["rows_removed"] == 0
    assert result["rows_added"] == 2

    header, rows = _csv_rows(catalog)
    assert header == before_header  # the target's own header always wins
    assert rows[: len(before_rows)] == before_rows  # pre-existing rows survive in order
    assert {row[0] for row in before_rows} == {"BMad Method", "Core"}
    assert [row[1] for row in rows if row[0] == "BMAD Loop Skills"] == [
        "bmad-loop-setup",
        "bmad-loop-sweep",
    ]
    assert result["total_rows"] == len(rows)


def test_merge_help_toml_catalog_merge_is_idempotent(tmp_path):
    """Two runs leave exactly one contiguous block of our rows (anti-zombie)."""
    bmad = _v610_bmad(tmp_path)
    catalog = bmad / "_config" / "bmad-help.csv"

    first = _merge_help(bmad, "--module-code", "bmad-loop")
    after_first = catalog.read_text()
    second = _merge_help(bmad, "--module-code", "bmad-loop")

    assert first["rows_removed"] == 0
    assert second["rows_removed"] == second["rows_added"] == first["rows_added"]
    assert second["total_rows"] == first["total_rows"]
    assert catalog.read_text() == after_first

    _, rows = _csv_rows(catalog)
    ours = [i for i, row in enumerate(rows) if row[0] == "BMAD Loop Skills"]
    assert len(ours) == 2
    assert ours == list(range(ours[0], ours[0] + 2))  # one block, not scattered


def test_merge_help_toml_creates_catalog_when_absent(tmp_path):
    """A missing catalog is created from the source header."""
    bmad = _v610_bmad(tmp_path)
    catalog = bmad / "_config" / "bmad-help.csv"
    catalog.unlink()

    result = _merge_help(bmad, "--module-code", "bmad-loop")

    assert result["catalog_existed"] is False
    assert result["rows_removed"] == 0
    source_header, source_rows = _csv_rows(ASSETS / "module-help.csv")
    header, rows = _csv_rows(catalog)
    assert header == source_header
    assert rows == source_rows


def test_merge_help_toml_leaves_root_csv_alone(tmp_path):
    """The inert root CSV is never written — only reported, and it survives (#64)."""
    bmad = _v610_bmad(tmp_path)
    root_csv = bmad / "module-help.csv"

    result = _merge_help(bmad, "--module-code", "bmad-loop")

    assert not root_csv.exists()  # the TOML branch never creates it
    assert result["orphans_detected"] == []
    assert "target_path" not in result

    # A pre-existing one is reported as an orphan and left byte-identical.
    seeded = "module,skill\nBMAD Automator Skills,bauto-sweep\n"
    root_csv.write_text(seeded)
    (bmad / "config.yaml").write_text("bmad-loop:\n  name: BMAD Loop Skills\n")

    result = _merge_help(bmad, "--module-code", "bmad-loop")

    orphans = {Path(o["path"]).name: o["has_module_entries"] for o in result["orphans_detected"]}
    assert orphans == {"config.yaml": True, "module-help.csv": True}
    assert root_csv.read_text() == seeded
    assert result["legacy_csvs_deleted"] == []


def test_merge_help_toml_strips_pre_rename_rows(tmp_path):
    """Pre-rename rows are NOT stripped — the filter keys on *source* module codes.

    The anti-zombie filter matches column 1 against the codes in the source CSV
    ("BMAD Loop Skills"), so rows a bmad-auto-era run left behind under
    "BMAD Automator Skills" never match and survive. Deleting them stays a manual
    step in SKILL.md's rename-migration section; asserted here so the docs
    describe what the code actually does.
    """
    bmad = _v610_bmad(tmp_path)
    catalog = bmad / "_config" / "bmad-help.csv"
    legacy_row = (
        "BMAD Automator Skills,bauto-sweep,Sweep Triage,ST,Legacy row.,"
        "triage,,anytime,,,false,,triage plan"
    )
    catalog.write_text(catalog.read_text() + legacy_row + "\n")

    result = _merge_help(bmad, "--module-code", "bmad-loop")

    assert result["rows_removed"] == 0  # nothing matched the source code
    _, rows = _csv_rows(catalog)
    assert [row[1] for row in rows if row[0] == "BMAD Automator Skills"] == ["bauto-sweep"]
    assert len([row for row in rows if row[0] == "BMAD Loop Skills"]) == 2


def test_merge_help_yaml_layout_unchanged(tmp_path):
    """No config.toml ⇒ today's single-target behavior, tagged layout == "yaml"."""
    bmad = _v6_bmad(tmp_path)
    assert not (bmad / "config.toml").exists()
    catalog_before = (bmad / "_config" / "bmad-help.csv").read_text()

    result = _merge_help(
        bmad,
        "--target",
        str(bmad / "module-help.csv"),
        "--legacy-dir",
        str(bmad),
        "--module-code",
        "bmad-loop",
    )

    assert result["layout"] == "yaml"
    assert result["orphans_detected"] == []
    assert result["legacy_csvs_deleted"] == []
    assert Path(result["target_path"]) == (bmad / "module-help.csv").resolve()
    assert result["target_existed"] is False
    assert result["module_codes"] == ["BMAD Loop Skills"]
    assert result["rows_added"] == 2

    _, rows = _csv_rows(bmad / "module-help.csv")
    assert [row[1] for row in rows] == ["bmad-loop-setup", "bmad-loop-sweep"]
    # nothing written where only the TOML layout would put it
    assert not (bmad / "bmad-loop" / "module-help.csv").exists()
    assert (bmad / "_config" / "bmad-help.csv").read_text() == catalog_before


def test_merge_help_layout_specific_args_are_required(tmp_path):
    """Each branch fails loudly when its layout-specific argument is missing."""
    toml_root = tmp_path / "v610"
    toml_root.mkdir()
    yaml_root = tmp_path / "v6"
    yaml_root.mkdir()

    proc = _run(
        "merge-help-csv.py",
        "--bmad-dir",
        str(_v610_bmad(toml_root)),
        "--source",
        str(ASSETS / "module-help.csv"),
    )
    assert proc.returncode == 1
    assert "--module-code" in json.loads(proc.stdout)["error"]

    legacy = _v6_bmad(yaml_root)
    proc = _run(
        "merge-help-csv.py",
        "--bmad-dir",
        str(legacy),
        "--source",
        str(ASSETS / "module-help.csv"),
    )
    assert proc.returncode == 1
    assert "--target" in json.loads(proc.stdout)["error"]
    assert not (legacy / "module-help.csv").exists()


# ------------------------------------- merge-config: TOML edit safety (PR #285 review)
#
# custom/config.toml is human-authored, so the module table is spliced in as a text
# edit. Finding the table's span with a regex is not safe, and getting it wrong is
# not a cosmetic bug: BMAD's resolve_config.py loads the custom layer as *optional*,
# so an unparseable file is swallowed as a warning and merged as {} — our table AND
# every override the user wrote there silently stop applying, with a zero exit code
# all the way down. Each layer below is valid TOML that a line-oriented regex
# mis-reads; every one of them used to come back invalid.

_HOSTILE_LAYERS = {
    # `]` is not the end of the line, so a `...\]\s*$` header match misses it and
    # appends a second [modules.bmad-loop] — a duplicate-table parse error.
    "inline_comment_header": '[modules.bmad-loop] # pinned by hand\nname = "old"\n',
    # The same table, spelled with quoted key components.
    "quoted_key_path": '["modules"."bmad-loop"]\nname = "old"\n',
    # A `[`-leading line *inside our own* multi-line string is not the next table:
    # cutting the span there strands the rest of the string.
    "multiline_basic_in_ours": (
        '[modules.bmad-loop]\nname = "old"\nnote = """\n[not a table]\nstill text\n"""\n'
        "\n[tool.other]\nx = 1\n"
    ),
    "multiline_literal_in_ours": (
        "[modules.bmad-loop]\nnote = '''\n[not a table]\n'''\n\n[tool.other]\nx = 1\n"
    ),
    # A header-shaped line inside someone *else's* string is not our table at all;
    # matching it clobbers their value.
    "our_header_inside_foreign_string": (
        '[agents.pm]\nnotes = """\n[modules.bmad-loop]\nfake = 1\n"""\n\n[tool.other]\nx = 1\n'
    ),
    # `#` inside a string does not start a comment.
    "hash_inside_string": '[tool.other]\nx = "a # b"\n\n[modules.bmad-loop]\nname = "old"\n',
    # A multi-line array's elements can start a line with `[`.
    "multiline_array": (
        '[tool.other]\nm = [\n  [1, 2],\n  [3, 4],\n]\n\n[modules.bmad-loop]\nname = "old"\n'
    ),
    "array_of_tables": (
        '[[bin]]\nname = "a"\n\n[[bin]]\nname = "b"\n\n[modules.bmad-loop]\nname = "old"\n'
    ),
    # Nothing to replace — the block is appended.
    "no_table_yet": "# just a comment\n\n[agents.pm]\nx = 1\n",
}


def _expected_after(before: dict, actual: dict) -> dict:
    """`before` with only modules.bmad-loop replaced by whatever we actually wrote.

    Comparing against this is the strongest statement of the edit's contract: the
    document may differ from the original in that one table and nowhere else.
    """
    expected = dict(before)
    modules = dict(expected.get("modules") or {})
    modules["bmad-loop"] = actual["modules"]["bmad-loop"]
    expected["modules"] = modules
    return expected


@pytest.mark.parametrize("layer_name", sorted(_HOSTILE_LAYERS))
def test_merge_config_toml_edit_never_corrupts_a_valid_layer(tmp_path, layer_name):
    """Valid TOML in, valid TOML out — and nothing but our table changed."""
    layer = _HOSTILE_LAYERS[layer_name]
    before = tomllib.loads(layer)  # every fixture is valid TOML to begin with
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    custom.write_text(layer)

    result = _merge_config(bmad, _answers(tmp_path, {}))

    text = custom.read_text()
    after = tomllib.loads(text)  # raises if the edit produced invalid TOML
    assert after == _expected_after(before, after)
    assert after["modules"]["bmad-loop"]["version"] == "0.9.0"
    # exactly one *table* — counting the literal would also match the fixture that
    # carries a header-shaped line inside a neighbour's multi-line string.
    headers = [h[2] for h in _load_script("merge-config.py").scan_table_headers(text)]
    assert headers.count(("modules", "bmad-loop")) == 1
    assert result["toml_validated"] is True


def test_merge_config_toml_preserves_footer_comments(tmp_path):
    """A comment after our table — the last in the file — is the file's, not ours.

    The trailing blank/comment back-off used to run only when another table
    followed, so a footer comment on the final table was swallowed by the span.
    """
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    custom.write_text('[modules.bmad-loop]\nname = "old"\n\n# keep this footer\n# and this line\n')

    _merge_config(bmad, _answers(tmp_path, {}))

    text = custom.read_text()
    assert "# keep this footer" in text
    assert "# and this line" in text
    assert text.count("[modules.bmad-loop]") == 1


@pytest.mark.parametrize("newline", ["\r\n", "\n"])
def test_merge_config_toml_preserves_newline_convention(tmp_path, newline):
    """A CRLF file stays CRLF (and an LF file stays LF), on every platform.

    Text-mode I/O translates on the way in *and* out, so a round-trip silently
    rewrote every line of a CRLF config — a whole-file diff for a one-table edit.
    """
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    custom.write_bytes(("# head" + newline + newline + "[agents.pm]" + newline).encode())

    _merge_config(bmad, _answers(tmp_path, {}))

    raw = custom.read_bytes()
    assert raw.count(b"\r\n") == (raw.count(b"\n") if newline == "\r\n" else 0)
    assert b"[modules.bmad-loop]" in raw
    assert tomllib.loads(custom.read_text())["modules"]["bmad-loop"]["version"] == "0.9.0"


@pytest.mark.skipif(sys.platform == "win32", reason="POSIX file modes")
def test_merge_config_toml_preserves_file_mode(tmp_path):
    """The atomic replace must carry the original mode; a fresh file would not."""
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    custom.chmod(0o640)

    _merge_config(bmad, _answers(tmp_path, {}))

    assert stat.S_IMODE(custom.stat().st_mode) == 0o640


def test_merge_config_toml_refuses_to_edit_an_unparseable_layer(tmp_path):
    """A config we cannot parse is a config we must not rewrite."""
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    broken = "[modules.bmad-loop\nname = "
    custom.write_text(broken)

    proc = _run(
        "merge-config.py",
        "--bmad-dir",
        str(bmad),
        "--module-yaml",
        str(ASSETS / "module.yaml"),
        "--answers",
        str(_answers(tmp_path, {})),
    )

    assert proc.returncode == 1
    error = json.loads(proc.stderr)
    assert error["status"] == "error"
    assert "not valid TOML" in error["error"]
    assert custom.read_text() == broken  # untouched


def test_merge_config_toml_refuses_a_candidate_that_changes_a_neighbour():
    """The verification gate is what makes the edit trustworthy, not the scanner.

    Sabotage the splice so it damages an unrelated table; the semantic diff must
    catch it and leave the file alone even though the result still parses.
    """
    merge_config = _load_script("merge-config.py")
    original = '[agents.pm]\nx = 1\n\n[modules.bmad-loop]\nname = "old"\n'
    block = merge_config.emit_module_table("bmad-loop", {"name": "New", "version": "9.9.9"})
    sabotaged = "[agents.pm]\nx = 2\n\n" + block  # neighbour silently rewritten

    error = merge_config.verify_candidate(original, sabotaged, "bmad-loop", block)

    assert error is not None
    assert "more than the [modules.bmad-loop] table" in error
    # ...and a faithful candidate is accepted
    faithful, _ = merge_config.upsert_module_table(original, "bmad-loop", block)
    assert merge_config.verify_candidate(original, faithful, "bmad-loop", block) is None


def test_merge_config_toml_tolerates_malformed_legacy_yaml(tmp_path):
    """The TOML branch discards legacy *values*, so it must not parse them.

    It used to, after the config had already been written: a malformed leftover
    raised, and the skill reported a failure for a registration that had succeeded.
    """
    bmad = _v610_bmad(tmp_path)
    (bmad / "core" / "config.yaml").write_text("user_name: [oops\n  bad: yaml\n")

    result = _merge_config(bmad, _answers(tmp_path, {}), None, "--legacy-dir", str(bmad))

    assert result["status"] == "success"
    assert str(bmad / "core" / "config.yaml") in result["legacy_configs_found"]
    assert result["legacy_configs_deleted"] == []
    custom = (bmad / "custom" / "config.toml").read_text()
    assert tomllib.loads(custom)["modules"]["bmad-loop"]["version"] == "0.9.0"


# --------------------------------- merge-help-csv: schema + commit safety (#285 review)


def test_merge_help_toml_maps_rows_by_column_name(tmp_path):
    """The catalog owns its header, so our rows are re-keyed into it by name.

    Appending positionally is only correct while the two schemas agree. BMAD has
    already renamed help columns once (`after`/`before` → `preceded-by`/`followed-by`),
    and a reorder would silently file every description under `skill`.
    """
    bmad = _v610_bmad(tmp_path)
    catalog = bmad / "_config" / "bmad-help.csv"
    # same columns, different order, plus one the source does not have
    catalog.write_text(
        "module,description,skill,display-name,menu-code,action,args,phase,"
        "preceded-by,followed-by,required,output-location,outputs,new-col\n"
        "Core,Show help.,bmad-help,Help,H,,,anytime,,,false,,,X\n"
    )

    result = _merge_help(bmad, "--module-code", "bmad-loop")

    header, rows = _csv_rows(catalog)
    assert header[:3] == ["module", "description", "skill"]  # catalog header preserved
    ours = {row[header.index("skill")]: row for row in rows if row[0] == "BMAD Loop Skills"}
    assert set(ours) == {"bmad-loop-setup", "bmad-loop-sweep"}
    setup_row = ours["bmad-loop-setup"]
    assert len(setup_row) == len(header)
    assert setup_row[header.index("display-name")] == "Setup Loop Module"
    assert setup_row[header.index("menu-code")] == "SA"
    assert "Install or update" in setup_row[header.index("description")]
    assert setup_row[header.index("new-col")] == ""  # no source value for it
    assert result["columns_dropped"] == []
    # the pre-existing row is untouched
    assert [r for r in rows if r[0] == "Core"][0][header.index("new-col")] == "X"


def test_merge_help_toml_reports_columns_the_catalog_cannot_hold(tmp_path):
    """A source column with no home in the catalog is dropped loudly, not silently."""
    bmad = _v610_bmad(tmp_path)
    catalog = bmad / "_config" / "bmad-help.csv"
    catalog.write_text("module,skill,display-name\nCore,bmad-help,Help\n")

    result = _merge_help(bmad, "--module-code", "bmad-loop")

    assert "description" in result["columns_dropped"]
    header, rows = _csv_rows(catalog)
    assert header == ["module", "skill", "display-name"]
    assert all(len(row) == 3 for row in rows)


def test_merge_help_toml_rejects_a_multi_module_source(tmp_path):
    """_bmad/<code>/module-help.csv is one module's file, by construction."""
    bmad = _v610_bmad(tmp_path)
    source = tmp_path / "mixed.csv"
    source.write_text(
        "module,skill,display-name,menu-code,description\n"
        "BMAD Loop Skills,bmad-loop-sweep,Sweep,ST,Ours.\n"
        "Some Other Module,other-skill,Other,OS,Theirs.\n"
    )
    catalog_before = (bmad / "_config" / "bmad-help.csv").read_text()

    proc = _run(
        "merge-help-csv.py",
        "--bmad-dir",
        str(bmad),
        "--source",
        str(source),
        "--module-code",
        "bmad-loop",
    )

    assert proc.returncode == 1
    assert "more than one module" in json.loads(proc.stdout)["error"]
    assert (bmad / "_config" / "bmad-help.csv").read_text() == catalog_before
    assert not (bmad / "bmad-loop" / "module-help.csv").exists()


# One marker, not two: stacked skipif conditions are *all* evaluated, so a separate
# os.geteuid() marker would raise at collection time on Windows. `or` short-circuits.
@pytest.mark.skipif(
    sys.platform == "win32" or os.geteuid() == 0,
    reason="needs POSIX directory permissions, and root ignores the write bit",
)
def test_merge_help_toml_never_truncates_the_shared_catalog(tmp_path):
    """A failed catalog write must leave the shared catalog byte-identical.

    _config/bmad-help.csv carries every module's help rows and is not hash-tracked
    in files-manifest.csv, so a truncating write there loses them all undetectably.
    """
    bmad = _v610_bmad(tmp_path)
    catalog = bmad / "_config" / "bmad-help.csv"
    before = catalog.read_bytes()
    (bmad / "_config").chmod(0o555)
    try:
        proc = _run(
            "merge-help-csv.py",
            "--bmad-dir",
            str(bmad),
            "--source",
            str(ASSETS / "module-help.csv"),
            "--module-code",
            "bmad-loop",
        )
    finally:
        (bmad / "_config").chmod(0o755)

    assert proc.returncode == 2
    assert json.loads(proc.stdout)["status"] == "error"
    assert catalog.read_bytes() == before
    assert not list((bmad / "_config").glob("*bmad-loop-tmp*"))


# ------------------------------------------------------- end-to-end: the real reader


def _deep_merge(base, override):
    """The scalar/table half of resolve_config.py's documented merge."""
    if isinstance(base, dict) and isinstance(override, dict):
        merged = dict(base)
        for key, value in override.items():
            merged[key] = _deep_merge(merged[key], value) if key in merged else value
        return merged
    return override


def _resolve_layers(bmad: Path) -> dict:
    """Resolve the four TOML layers exactly as BMAD's resolver documents them.

    A local oracle so CI can assert the end-to-end result: `_bmad/` is gitignored,
    so a checkout never carries BMAD's own resolve_config.py (the test below runs
    the real one when a project tree happens to provide it).
    """
    merged: dict = {}
    for name in (
        "config.toml",
        "config.user.toml",
        "custom/config.toml",
        "custom/config.user.toml",
    ):
        path = bmad / name
        if path.is_file():
            merged = _deep_merge(merged, tomllib.loads(path.read_text(encoding="utf-8")))
    return merged


def test_registration_resolves_through_the_four_layer_merge(tmp_path):
    """What BMAD actually reads back after setup runs — twice, for idempotence."""
    bmad = _v610_bmad(tmp_path)
    answers = _answers(tmp_path, {})
    custom_before = (bmad / "custom" / "config.toml").read_text()

    for _ in range(2):
        _merge_config(bmad, answers)
        _merge_help(bmad, "--module-code", "bmad-loop")

    resolved = _resolve_layers(bmad)
    table = resolved["modules"]["bmad-loop"]
    assert table["name"] == "BMAD Loop Skills"
    assert table["version"] == "0.9.0"
    assert table["default_selected"] is False
    # the installer layer still wins where we wrote nothing
    assert resolved["core"]["user_name"] == "BMad"
    assert resolved["modules"]["bmm"]["name"] == "BMad Method"
    # the human-authored layer we edited is otherwise intact
    assert resolved["modules"]["my-thing"]["enabled"] is True
    assert (bmad / "custom" / "config.toml").read_text().startswith(custom_before)

    _, rows = _csv_rows(bmad / "_config" / "bmad-help.csv")
    assert len([row for row in rows if row[0] == "BMAD Loop Skills"]) == 2


def test_registration_resolves_through_bmads_own_resolver(tmp_path):
    """Same assertion against BMAD's real resolve_config.py, when one is available.

    Skipped in CI (a checkout has no `_bmad/`); set BMAD_RESOLVE_CONFIG to a real
    installed copy to exercise the genuine reader instead of the oracle above.
    """
    resolver = os.environ.get("BMAD_RESOLVE_CONFIG") or str(
        REPO / "_bmad" / "scripts" / "resolve_config.py"
    )
    if not Path(resolver).is_file():
        pytest.skip("no BMAD resolve_config.py available (set BMAD_RESOLVE_CONFIG)")

    bmad = _v610_bmad(tmp_path)
    _merge_config(bmad, _answers(tmp_path, {}))

    proc = subprocess.run(
        [sys.executable, resolver, "--project-root", str(tmp_path), "--key", "modules.bmad-loop"],
        capture_output=True,
        text=True,
    )

    assert proc.returncode == 0, proc.stderr
    # a layer it could not parse would be warned about and merged as {}
    assert "failed to parse" not in proc.stderr
    assert json.loads(proc.stdout)["modules.bmad-loop"]["version"] == "0.9.0"
