"""Regression guard for bmad-loop#64: the bmad-loop-setup cleanup scripts must
never delete live, manifest-tracked BMAD config/state.

On a BMAD v6 install ``_bmad/core/``, ``_bmad/<module>/`` and ``_bmad/_config/``
hold live config + installer manifests (no staged ``SKILL.md``). The setup scripts
used to hardcode ``core`` and ``--also-remove _config`` into their delete lists,
destroying that shared state. These tests run the real scripts as the SKILL.md
documents and assert only genuine redundant skill-payload dirs are ever removed.

Root cause is shared with upstream ``bmad-code-org/bmad-builder#96``.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tomllib
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "src" / "bmad_loop" / "data" / "skills" / "bmad-loop-setup" / "scripts"
ASSETS = REPO / "src" / "bmad_loop" / "data" / "skills" / "bmad-loop-setup" / "assets"


def _run(script: str, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPTS / script), *args],
        capture_output=True,
        text=True,
    )


def _run_json(script: str, *args: str) -> dict:
    proc = _run(script, *args)
    assert (
        proc.returncode == 0
    ), f"{script} exit {proc.returncode}\nOUT:{proc.stdout}\nERR:{proc.stderr}"
    return json.loads(proc.stdout)


def _v6_bmad(tmp_path: Path) -> Path:
    """A realistic BMAD v6 `_bmad/` tree: live config + manifest, no staged skills."""
    bmad = tmp_path / "_bmad"
    (bmad / "core").mkdir(parents=True)
    (bmad / "core" / "config.yaml").write_text("user_name: BMad\noutput_folder: out\n")
    (bmad / "core" / "module-help.csv").write_text("module,skill\ncore,x\n")
    (bmad / "bmm").mkdir()
    (bmad / "bmm" / "config.yaml").write_text("dev_story_location: docs\n")
    (bmad / "bmad-loop").mkdir()
    (bmad / "bmad-loop" / "config.yaml").write_text("cadence: fast\n")
    cfg = bmad / "_config"
    cfg.mkdir()
    (cfg / "manifest.yaml").write_text("installation:\n  version: 6.10.0\n")
    (cfg / "files-manifest.csv").write_text("path,hash\n_bmad/core/config.yaml,abc\n")
    (cfg / "bmad-help.csv").write_text("module,skill\ncore,x\n")
    return bmad


# A human-authored custom layer: comments, blank lines, an unrelated table.
# BMAD documents _bmad/custom/config.toml as the layer the installer never touches,
# so merge-config must edit it surgically and leave everything else byte-identical.
_CUSTOM_TOML = """\
# Custom overrides — the BMAD installer never touches this file.
# Values here win over the generated layers.

[modules.my-thing]
# hand-written note about my-thing
enabled = true
"""


def _v610_bmad(tmp_path: Path) -> Path:
    """A BMAD v6.10 `_bmad/` tree: consolidated TOML config + a custom layer.

    Same live per-module YAML as `_v6_bmad` (v6.10 still ships those and the
    manifest still tracks them) plus the four TOML layers the v6.10 resolver
    actually reads. The presence of `config.toml` is what selects the layout.
    """
    bmad = _v6_bmad(tmp_path)
    (bmad / "config.toml").write_text(
        "# Generated by the BMAD installer.\n"
        "[core]\n"
        'user_name = "BMad"\n'
        'output_folder = "out"\n'
        "\n"
        "[modules.bmm]\n"
        'name = "BMad Method"\n'
        'version = "6.10.0"\n'
    )
    (bmad / "config.user.toml").write_text('[core]\nuser_name = "BMad"\n')
    (bmad / "custom").mkdir()
    (bmad / "custom" / "config.toml").write_text(_CUSTOM_TOML)
    return bmad


def _answers(tmp_path: Path, payload: dict) -> Path:
    path = tmp_path / "answers.json"
    path.write_text(json.dumps(payload))
    return path


def _merge_config(bmad: Path, answers: Path, module_yaml: Path | None = None, *extra: str) -> dict:
    return _run_json(
        "merge-config.py",
        "--bmad-dir",
        str(bmad),
        "--module-yaml",
        str(module_yaml or ASSETS / "module.yaml"),
        "--answers",
        str(answers),
        *extra,
    )


def _skills_dir(tmp_path: Path, *installed: str) -> Path:
    skills = tmp_path / ".claude" / "skills"
    skills.mkdir(parents=True)
    for name in installed:
        d = skills / name
        d.mkdir()
        (d / "SKILL.md").write_text(f"# {name}\n")
    return skills


# ---------------------------------------------------------------- cleanup-legacy


def test_cleanup_preserves_core_and_config_on_v6(tmp_path):
    """The documented invocation must be a no-op on a v6 install."""
    bmad = _v6_bmad(tmp_path)
    skills = _skills_dir(tmp_path)  # nothing installed — bmad-loop dir is config-bearing

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "bmad-loop",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == []
    assert (bmad / "bmad-loop" / "config.yaml").exists()
    assert (bmad / "core" / "config.yaml").exists()
    assert (bmad / "_config" / "manifest.yaml").exists()
    protected = {p["dir"] for p in result["directories_protected"]}
    assert "bmad-loop" in protected


def test_cleanup_refuses_explicit_core_and_config(tmp_path):
    """Even an explicit --module-code core / --also-remove _config must not delete them."""
    bmad = _v6_bmad(tmp_path)
    skills = _skills_dir(tmp_path)

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "core",
        "--also-remove",
        "_config",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == []
    assert (bmad / "core" / "config.yaml").exists()
    assert (bmad / "_config" / "manifest.yaml").exists()
    assert (bmad / "_config" / "files-manifest.csv").exists()


def test_cleanup_removes_genuine_redundant_payload(tmp_path):
    """A dir with an installed SKILL.md payload and no config IS cleaned."""
    bmad = _v6_bmad(tmp_path)
    payload = bmad / "legacy-mod"
    payload.mkdir()
    (payload / "SKILL.md").write_text("# legacy-mod\n")  # skill name == 'legacy-mod'
    skills = _skills_dir(tmp_path, "legacy-mod")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy-mod",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == ["legacy-mod"]
    assert not payload.exists()
    # protecting v6 state is unaffected
    assert (bmad / "core" / "config.yaml").exists()


def test_cleanup_errors_when_payload_skill_not_installed(tmp_path):
    """A payload dir whose skill is missing from skills-dir is an error, not a delete."""
    bmad = _v6_bmad(tmp_path)
    payload = bmad / "legacy-mod"
    payload.mkdir()
    (payload / "SKILL.md").write_text("# legacy-mod\n")
    skills = _skills_dir(tmp_path)  # legacy-mod NOT installed

    proc = _run(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy-mod",
        "--skills-dir",
        str(skills),
    )
    assert proc.returncode == 1
    assert payload.exists()
    err = json.loads(proc.stdout)
    assert err["status"] == "error"
    assert "legacy-mod" in err["missing_skills"]


def test_cleanup_reports_removable_dir_absent_at_removal_time(tmp_path):
    """A removable dir gone by removal time must surface in directories_not_found.

    Regression for bmad-loop#73 review: cleanup_directories()'s not_found used to be
    discarded, so such a dir silently vanished from every JSON list. Exercised
    deterministically via a nested --also-remove target whose parent is removed first.
    """
    bmad = _v6_bmad(tmp_path)
    # 'legacy/' has no SKILL.md of its own; its only payload is 'legacy/child'.
    (bmad / "legacy" / "child").mkdir(parents=True)
    (bmad / "legacy" / "child" / "SKILL.md").write_text("# child\n")
    skills = _skills_dir(tmp_path, "child")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy",
        "--also-remove",
        "legacy/child",  # removed together with its parent 'legacy' earlier in the run
        "--skills-dir",
        str(skills),
    )

    # Parent is removed; the nested child is already gone by its turn but must still
    # be reported rather than silently dropped from all output lists.
    assert result["directories_removed"] == ["legacy"]
    assert "legacy/child" in result["directories_not_found"]
    assert not (bmad / "legacy").exists()


def test_cleanup_protects_core_by_name_even_as_pure_payload(tmp_path):
    """core/ is never removed — even holding only a SKILL.md payload and no config.

    Regression for bmad-loop#73 review: the docstring promised 'core' is never
    removed, but only _config was protected by name; a marker-less core payload
    slipped through the config-bearing check.
    """
    bmad = tmp_path / "_bmad"
    core = bmad / "core"
    core.mkdir(parents=True)
    (core / "SKILL.md").write_text("# core\n")  # no config markers at all
    skills = _skills_dir(tmp_path, "core")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "core",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == []
    assert (core / "SKILL.md").exists()
    protected = {p["dir"] for p in result["directories_protected"]}
    assert "core" in protected


def test_cleanup_protects_dir_with_nested_live_config(tmp_path):
    """A config marker nested below the top level still protects the whole dir.

    Regression for bmad-loop#73 review: is_config_bearing() only looked at the
    candidate's top level while skill discovery was recursive, so a dir with a
    SKILL.md and deeper live config was misclassified as a removable payload.
    """
    bmad = _v6_bmad(tmp_path)
    legacy = bmad / "legacy-mod"
    (legacy / "sub").mkdir(parents=True)
    (legacy / "SKILL.md").write_text("# legacy-mod\n")
    (legacy / "sub" / "config.yaml").write_text("live: true\n")  # nested live state
    skills = _skills_dir(tmp_path, "legacy-mod")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy-mod",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == []
    assert (legacy / "sub" / "config.yaml").exists()
    protected = {p["dir"] for p in result["directories_protected"]}
    assert "legacy-mod" in protected


def test_cleanup_removes_payload_whose_skill_ships_marker_named_assets(tmp_path):
    """Marker-named files inside a SKILL.md-bearing subtree are payload, not live state.

    Staged skill payloads legitimately ship files like assets/module-help.csv
    (bmad-loop-setup itself does); the recursive config scan must not
    false-protect such a dir or the documented bauto rename-cleanup would no-op.
    """
    bmad = _v6_bmad(tmp_path)
    legacy = bmad / "legacy-mod"
    foo = legacy / "skills" / "foo"
    (foo / "assets").mkdir(parents=True)
    (foo / "SKILL.md").write_text("# foo\n")
    (foo / "assets" / "module-help.csv").write_text("module,skill\nfoo,x\n")
    skills = _skills_dir(tmp_path, "foo")

    result = _run_json(
        "cleanup-legacy.py",
        "--bmad-dir",
        str(bmad),
        "--module-code",
        "legacy-mod",
        "--skills-dir",
        str(skills),
    )

    assert result["directories_removed"] == ["legacy-mod"]
    assert not legacy.exists()
    # live v6 state is untouched
    assert (bmad / "core" / "config.yaml").exists()


# ---------------------------------------------------------------- merge-config


def test_merge_config_preserves_legacy_configs(tmp_path):
    bmad = _v6_bmad(tmp_path)
    answers = tmp_path / "answers.json"
    answers.write_text("{}")

    result = _run_json(
        "merge-config.py",
        "--bmad-dir",
        str(bmad),
        "--config-path",
        str(bmad / "config.yaml"),
        "--user-config-path",
        str(bmad / "config.user.yaml"),
        "--module-yaml",
        str(ASSETS / "module.yaml"),
        "--answers",
        str(answers),
        "--legacy-dir",
        str(bmad),
    )

    assert result["legacy_configs_deleted"] == []
    # live per-module + core config survive
    assert (bmad / "core" / "config.yaml").exists()
    assert (bmad / "bmad-loop" / "config.yaml").exists()
    # and the consolidated config was still written
    assert (bmad / "config.yaml").exists()


# --------------------------------------------------- merge-config (toml layout)
#
# bmad-loop#258: BMAD v6.10 consolidated onto TOML and its resolver reads only
# config.toml / config.user.toml / custom/config.toml / custom/config.user.toml.
# Registration must land in custom/config.toml — and nowhere else.


def test_merge_config_toml_layout_writes_custom_table(tmp_path):
    """The module table lands in custom/config.toml and BMAD's own reader accepts it."""
    bmad = _v610_bmad(tmp_path)

    result = _merge_config(bmad, _answers(tmp_path, {}))

    assert result["status"] == "success"
    assert result["layout"] == "toml"
    assert result["table_replaced"] is False
    assert result["toml_validated"] is True
    custom = bmad / "custom" / "config.toml"
    assert Path(result["config_path"]) == custom.resolve()
    assert set(result["module_keys"]) == {"name", "description", "version", "default_selected"}

    text = custom.read_text()
    assert "[modules.bmad-loop]" in text
    assert 'name = "BMAD Loop Skills"' in text
    assert 'version = "0.9.0"' in text
    assert "default_selected = false" in text

    table = tomllib.loads(text)["modules"]["bmad-loop"]
    assert table["name"] == "BMAD Loop Skills"
    assert table["version"] == "0.9.0"
    assert table["default_selected"] is False
    assert table["description"].startswith("Automation-mode skills")


def test_merge_config_toml_layout_preserves_custom_comments(tmp_path):
    """Every pre-existing comment and unrelated table survives verbatim.

    custom/config.toml is human-authored; the edit is surgical, never a
    parse-and-re-emit. Covers both an append (no table yet) and a replace with a
    following commented table — whose preamble belongs to *it*, not to our span.
    """
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    answers = _answers(tmp_path, {})

    _merge_config(bmad, answers)

    after_append = custom.read_text()
    assert after_append.startswith(_CUSTOM_TOML)
    for line in _CUSTOM_TOML.splitlines():
        assert line in after_append.splitlines()

    # Now our table has a hand-written neighbour *below* it.
    trailing = "\n# notes that belong to the next table\n[tool.something]\nx = 1\n"
    custom.write_text(after_append + trailing)

    result = _merge_config(bmad, answers)

    final = custom.read_text()
    assert result["table_replaced"] is True
    assert final.count("[modules.bmad-loop]") == 1
    assert final.startswith(_CUSTOM_TOML)
    assert final.endswith(trailing)
    assert "# notes that belong to the next table" in final
    assert tomllib.loads(final)["tool"]["something"]["x"] == 1


def test_merge_config_toml_layout_writes_no_yaml(tmp_path):
    """No config.yaml / config.user.yaml is created, and the installer layer is untouched."""
    bmad = _v610_bmad(tmp_path)
    installer_toml = (bmad / "config.toml").read_text()

    result = _merge_config(bmad, _answers(tmp_path, {}))

    assert not (bmad / "config.yaml").exists()
    assert not (bmad / "config.user.yaml").exists()
    assert result["user_config_path"] is None
    assert result["user_keys"] == []
    # installer-owned layers are read-only to us
    assert (bmad / "config.toml").read_text() == installer_toml
    assert (bmad / "config.user.toml").read_text() == '[core]\nuser_name = "BMad"\n'


def test_merge_config_toml_layout_never_writes_core_values(tmp_path):
    """Core answers leave no trace: the custom layer wins over the installer layer.

    Pinning user_name / output_folder here would override every future installer
    answer, so on the TOML layout core config stays installer-owned.
    """
    bmad = _v610_bmad(tmp_path)
    answers = _answers(
        tmp_path,
        {
            "core": {
                "user_name": "Zaphod",
                "output_folder": "docs/generated",
                "communication_language": "Betelgeusian",
            }
        },
    )

    result = _merge_config(bmad, answers)

    text = (bmad / "custom" / "config.toml").read_text()
    for leaked in ("Zaphod", "user_name", "output_folder", "Betelgeusian"):
        assert leaked not in text
    assert result["core_updated"] is False
    assert result["user_keys"] == []
    assert not (bmad / "config.user.yaml").exists()


def test_merge_config_toml_upsert_is_idempotent(tmp_path):
    """Two runs leave exactly one table; a version bump replaces, never duplicates."""
    bmad = _v610_bmad(tmp_path)
    custom = bmad / "custom" / "config.toml"
    answers = _answers(tmp_path, {})

    first = _merge_config(bmad, answers)
    second = _merge_config(bmad, answers)

    assert first["table_replaced"] is False
    assert second["table_replaced"] is True
    assert custom.read_text().count("[modules.bmad-loop]") == 1

    bumped = tmp_path / "module.yaml"
    bumped.write_text(
        (ASSETS / "module.yaml")
        .read_text()
        .replace("module_version: 0.9.0", "module_version: 1.2.3")
    )
    third = _merge_config(bmad, answers, bumped)

    text = custom.read_text()
    assert third["table_replaced"] is True
    assert text.count("[modules.bmad-loop]") == 1
    assert 'version = "1.2.3"' in text
    assert '"0.9.0"' not in text
    assert tomllib.loads(text)["modules"]["bmad-loop"]["version"] == "1.2.3"


def test_merge_config_toml_reports_orphans_without_deleting(tmp_path):
    """Inert pre-6.10 leftovers are reported, never removed (bmad-loop#64)."""
    bmad = _v610_bmad(tmp_path)
    (bmad / "config.yaml").write_text("bmad-loop:\n  name: BMAD Loop Skills\n")
    (bmad / "module-help.csv").write_text("module,skill\nBMAD Automator Skills,bauto-sweep\n")
    # a malformed leftover must be reported, not raised on
    (bmad / "config.user.yaml").write_text("this: [is: not: valid\n")

    result = _merge_config(bmad, _answers(tmp_path, {}), None, "--legacy-dir", str(bmad))

    orphans = {Path(o["path"]).name: o["has_module_entries"] for o in result["orphans_detected"]}
    assert orphans == {
        "config.yaml": True,
        "config.user.yaml": False,
        "module-help.csv": True,
    }
    assert result["legacy_configs_deleted"] == []
    # every reported orphan survives, byte for byte
    assert (bmad / "config.yaml").read_text() == "bmad-loop:\n  name: BMAD Loop Skills\n"
    assert (bmad / "config.user.yaml").exists()
    assert (bmad / "module-help.csv").exists()
    # ...as does the live per-module config --legacy-dir reads
    assert (bmad / "core" / "config.yaml").exists()
    assert (bmad / "bmad-loop" / "config.yaml").exists()


def test_merge_config_yaml_layout_unchanged(tmp_path):
    """No config.toml ⇒ today's legacy behavior, tagged layout == "yaml"."""
    bmad = _v6_bmad(tmp_path)
    assert not (bmad / "config.toml").exists()

    result = _merge_config(
        bmad,
        _answers(tmp_path, {"core": {"user_name": "BMad"}}),
        None,
        "--config-path",
        str(bmad / "config.yaml"),
        "--user-config-path",
        str(bmad / "config.user.yaml"),
        "--legacy-dir",
        str(bmad),
    )

    assert result["layout"] == "yaml"
    assert result["orphans_detected"] == []
    assert result["legacy_configs_deleted"] == []
    assert result["module_code"] == "bmad-loop"
    assert result["core_updated"] is True
    assert result["user_keys"] == ["user_name"]
    assert (bmad / "config.yaml").exists()
    assert (bmad / "config.user.yaml").exists()
    assert not (bmad / "custom").exists()

    config = yaml.safe_load((bmad / "config.yaml").read_text())
    assert config["bmad-loop"]["name"] == "BMAD Loop Skills"


def test_merge_config_yaml_layout_requires_legacy_paths(tmp_path):
    """The legacy branch fails loudly when its layout-specific paths are missing."""
    bmad = _v6_bmad(tmp_path)

    proc = _run(
        "merge-config.py",
        "--bmad-dir",
        str(bmad),
        "--module-yaml",
        str(ASSETS / "module.yaml"),
        "--answers",
        str(_answers(tmp_path, {})),
    )

    assert proc.returncode == 1
    error = json.loads(proc.stderr)
    assert error["status"] == "error"
    assert "--config-path" in error["error"]
    assert not (bmad / "config.yaml").exists()


# ---------------------------------------------------------------- merge-help-csv


def test_merge_help_csv_preserves_legacy_csvs(tmp_path):
    bmad = _v6_bmad(tmp_path)

    result = _run_json(
        "merge-help-csv.py",
        "--target",
        str(bmad / "module-help.csv"),
        "--source",
        str(ASSETS / "module-help.csv"),
        "--legacy-dir",
        str(bmad),
        "--module-code",
        "bmad-loop",
    )

    assert result["legacy_csvs_deleted"] == []
    assert (bmad / "core" / "module-help.csv").exists()
    assert (bmad / "module-help.csv").exists()
